# TODO Create your inputs, variables, and add your story here!
noun = input("Enter a noun: ")
adjective= input("Enter an adjective: ")
verb= input("Enter a verb: ")
location= input("Enter a place: ")
color= input("Enter a color: ")
clothing= input("Enter an aritcle of clothing: ")
item= input("Enter a random item that starts with a consonant: ")
person= input("Enter a person: ")
drink= input("Enter a drink: ")
book= input("Enter a book title: ")
food= input("Enter a food item: ")
song= input("Enter a song title: ")
nature= input("Enter something that grows out of the ground: ")
print(f" The {noun} was {adjective} while {verb} at {location}. {noun} was wearing a {color} {clothing} while talking to a {item}.")
print(f"{person} saw {noun} talking to a {item} so {person} offerd {noun} a {drink}. {person} was also holding {book} in their hands. {noun} stole the book and ran away.")
print(f"Luckily {noun} did not steal {person}'s {food}. So {person} and {item} sat by a {nature} while lsitening to {song} and eating {food}.")